---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Configure Puppet 6 repositories
      ansible.builtin.include_role:
        name: puppet_repositories
      vars:
        foreman_puppet_repositories_version: 6
